[package]
name = "zerosim-trace"
version = "0.1.0"
authors = ["Mark Mansi <markm@cs.wisc.edu>"]
edition = "2018"

[dependencies]
libc = "0.2.51"
itertools = "0.8.0"
clap = "2.33.0"
failure = "0.1.5"
lazy_static = "1.3.0"
regex = "1.1.6"
